name: colombia_datos_y_iss
description: "Portal Territorial de Colombia, Clima y Rastreo de la ISS."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  syncfusion_flutter_gauges: 33.2.10
  shared_preferences: ^2.5.5
  js: ^0.7.2
  geolocator: ^11.0.0 # <--- NUEVA: Obligatoria para obtener las coordenadas GPS del dispositivo
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/colombia_data.json